namespace SpoongePE.Core.Network;

public enum MinecraftPacketType : byte {
    // Who can send it?
    Unknown = 0x00, // Server (for split packets)
    LoginRequest = 0x82, // Client
    LoginResponse = 0x83, // Server
    Ready = 0x84, // Client
    Message = 0x85, // Both
    SetTime = 0x86, // Server
    StartGame = 0x87, // Server
    AddMob = 0x88, // Server
    AddPlayer = 0x89, // Server
    RemovePlayer = 0x8A, // Server
    AddEntity = 0x8C, // Server
    RemoveEntity = 0x8D, // Server
    AddItemEntity = 0x8E, // Server
    TakeItemEntity = 0x8F, // Server?
    MoveEntity = 0x90, // Unused?
    MoveEntityPosRot = 0x93, // Server
    RotateHead = 0x94, // Server
    MovePlayer = 0x95, // Both
    PlaceBlock = 0x96, // Both
    RemoveBlock = 0x97, // Both
    UpdateBlock = 0x98, // Server?
    AddPainting = 0x99, // Server
    Explode = 0x9A, // Server
    LevelEvent = 0x9B, // Server
    TileEvent = 0x9C, // Server
    EntityEvent = 0x9D, // Server
    RequestChunk = 0x9E, // Client
    ChunkData = 0x9F, // Server
    PlayerEquipment = 0xA0, // Both
    PlayerArmorEquipment = 0xA1, // Both?
    Interact = 0xA2, // Client
    UseItem = 0xA3, // Client
    PlayerAction = 0xA4, // Client
    HurtArmor = 0xA6, // Server
    SetEntityData = 0xA7, // Server
    SetEntityMotion = 0xA8, // Server
    SetRiding = 0xA9, // Server
    SetHealth = 0xAA, // Server
    SetSpawnPosition = 0xAB, // Server
    Animate = 0xAC, // Server
    Respawn = 0xAD, // Client
    SendInventory = 0xAE, // Unused
    DropItem = 0xAF, // Client
    ContainerOpen = 0xB0, // Both?
    ContainerClose = 0xB1, // Both?
    ContainerSetSlot = 0xB2, // Server?
    ContainerSetData = 0xB3, // Server?
    ContainerSetContent = 0xB4, // Server?
    ContainerAck = 0xB5, // Both
    Chat = 0xB6, // Both
    AdventureSettings = 0xB7, // Server // ADVENTURE_SETTINGS_PACKET // SignUpdate??
    SetTileEntityData = 0xB8, // Server/Both?
    PlayerInput = 0xB9, // Client
    DATA_PACKET_0 = 0x80 // Unk
}
